/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: aacbfca9926485046592144d7b852efe)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	CITY_HISTORY_ESTIMATES: D1Database;
	CITY_HISTORY_PROJECTIONS: D1Database;
	PUBLICATIONS_DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
